language: groovy
jdk:
- oraclejdk8
install:
- echo "skiping 'install' step"
script:
- ./gradlew check bintrayUpload
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - secure: bDgDgJncek7XivvlJf3LWfA7GIP+GTaZf150cmKnLHInpoOeNhkIKlx8byHDwR2Y8hrgWizUPYeBUQnQ/02fPqrRCjuZvYZRQP7p8O1jnLGcKbLGwhT4Dw7K8v4eZk6bFOdeed6MXMN9iDaqCUNeBG4Pny3/evsDBZ60mzuEaVrHKEVTnHmHSHjI7iDcQo/IwlWMTb2cp+9txxtbU/Oc3+mc9JbjTMVweTGxI8gdnxyNLi2Q5DU38+REM+X5dDcv7x7vp9jyeCaUQ+PSW3mCwAr/qx80XORlp9sjpWjci50MuJQYSVoy4CQ4OETx8Sxs7bAQlbHMxT4L84B2aKychXpFwokmv5TEFQuNnLnUtkHPFNVOnvz4bzl/lIJviSt3Ix/68OFIVEDjDMLe9pN+IxJlVNYD/nWsu7c0e9bG1guk+kCvecl7WLz1CUy8thkvEHmPCoQU908QFeCfg1a9X5aa0TGiyqxxabGQZXpEMOIccnmdp2c/k07K4j2AuzPYlRlVKiKbLnRlStMStSHtS39ZtE67J8n86KX45oHBs1r3Q3YlL7cemVSkGUydbOwMLlmvuPv/Dptl+BWjTeX+Xd9afnP3djQnRXkpE+VEjj5adYKw9++Ma2zNikRHGnQRhr6BgkB70zdx+dl0IBNHIbFJM2WI0F9l4444BgXxO1A=
  - secure: JexWDpK9rHWuDeS0KaiDoxsWMRnXbM+u1+HIUAA26ZpBLYyu57ttX0PtxRNtFLAftazfRztlaYuMCUngRo9qXAvmXym4vARPRql4LE9CDxIm2IwzFAVKHdh3bsOaPWhYR0JsQL+RRRN4jyxGbAPMSVih6FWOzBrKN3xpI1ByL5dBlx+/c6Oy9uk88xcQXkTuxTxNj39+lU+SGReK3nBrhmetwEuoj2htIF4QwgIq7XddaGQr730RKdcnweADw/aIfs88XYOTM/5Jyc0PxOmd1RX9wstjrYhB330BtojW6qhXQokTHqVklxk63oB1xabDnHnwRiafaPhloBLOcApRYg/9FfhxIOl+3WedtPbHoTH0/UMMmlERUzJ8WgmYwLHeQVF72UvhH6PlmHkRVPSnCt5vsy90Au330BTmQ7hkAjDUqWnU811TBBP8oKLOu4K899Q9NtcQFLAoGnVkgbBhQDKNMFUdJ1F0WXnQsc3MmvV8UJu2raNuaIsnojDOs3x8dea+q1/4UeLGhVOZiPPltdVAsRR3wfF+eMdNjCbw0F2QfEcm/LrtRamL6mU0VGNMq0ObJ06Dzw0RNaYxg7TgvsENxy87WjA2Jue9EgJV4gTmJm2GnsQbPIvtq/3C8HyhGHFGIdi6a71AmiTwmaj73s/AaO1/S3ccqQ68iDY7wo0=
