language: groovy
jdk:
- oraclejdk8
install:
- echo "skiping 'install' step"
script:
- gradle check bintrayUpload
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - secure: W4FKwDvuHjaqif9TpWkQsTUsmlhadCqmxCDO5GFStv8ULDO1/OOC4W5QBZv/6cWpzFuJqRJ4aHy+kp/aQLQK5XozH6SXFXn9Vv39d6qQ9T+m8nra6L0WOJx9+C8bleFTOIHMXtYsPlH7ZKpwXkvxaDAwLFapDggc3+BfdVwlLRc9rDhaZIdnplq9sxhWHHFPVAbbkABBMv79QnVJTxRB077oi/9E088rctC47LBaeXoVDsuNn1oFe2uPjJJ0rgmNHhCyYQshYomJaF/CqXRdDuRo+SxO77oxUiNFo5FXZY/8YqBZgV99EoSsg+xn7c5QKceDHQhtICg8ngygNCwtse/o321Y0V5NVg7bR9wGQgEH8/IE2PZa/zb6J6iU/JYeWgLPLvO6OdEn/4P/G0yHjbE0POKC/FqtD+Sz7vNBrrhdaw3wuaIGxmaxHaIQhNXPxKgeZXAPrA1bqNvIC6N9GKRmLWMqa8V+LQGGV+RZ/7lFdVK5FW1xaAzOPF8KepRKxW6UkikjvMgOfp1UrhXhaiqVK9CTXJytFp7D0BKyYSAwLW8OYvZzAPejgW9zgCGa+CqySu+QA4+eFv5762MKxS7QaiIwaazxV3P8P0THXc+PWkezeudKoBogUP/zsugW1H7EBxHJ/zuykNzEQtjXVFawa1bwJayTiUZN/kzxwu4=
  - secure: P0zdAn53KfvE10f1ELxK7S6gnbPyC390hq66t+gT+2lEpUJ+2oJ59NarWtRdJzEyjnmr67o7xBQfTA/FYC36v6+K7OeFYgP5bEp1Mp2f0tsJIsTjmHJzK/3oKGUhvJemEEBZs5Kvf6vaEFtl9gh0s7w9ssGm8UKJ6ytFsEtWFVmlPs+27GZIE/v6y8Uzt5DSwG3eLOZvRlNatM5ERN9XI5iz47M6/Ce5xZBLSZ9Ove1RO0xUcOOTLuYD29DvbZvGCqMMSC9N458DKO5kEf4cMyN7Wm2VB83gOsDy9Xz5FHk5pZadfrMmDRtaFhwna+RvM0oZYtdxUT8zOZymroJ6R+wwTZ+oQbzEK3QVvp8SAYg5IaSbuYzAADHUKPqh2Crd5r2ep/kPlO/tBScuRYSN//MsClpu9aazCVtW765qU7D9T7bCp43AeXKjbHNQdAZL4Q1LFRQpxvFUI7HfPsx8BYBYPaRNs6lpV+/7Nc+eeqPdz7YNpFzK6p4mlpIbEHyURm7jPEO1RvCYuzPKZJDkk1QP5cy9Hc9owoPNvyHkl2wjbhHNfOSY5jnPKm7utLRe8OvQBT5WidwiYC/91j+c4fAbJZmKGmSZaH2/JfyNax/C/3xaiJUTIqX1D2yZjUbC7H8Jvme6ePhncYLPt5jAZdvmLsK1FsnzSDMmKWDsbHc=
